include { IRODS_QUERY; CRAM_EXTRACT      } from '../assorted-sub-workflows/irods_extractor/subworkflows/irods.nf'

workflow CHECK_EXISTS_IRODS_EXTRACT {
    
    take:
    input_irods_ch //tuple studyid, runid, laneid, plexid

    main:
    IRODS_QUERY(input_irods_ch)

    IRODS_QUERY.out.set{ meta_cram_ch }

    // check existence of files generated by Kneaddata as these are the ones we want to keep always
    Channel.fromPath("${params.outdir}/*#*/trimmed_reads/*_1.fastq.gz").map{ trimmed_reads_path ->
        ID = trimmed_reads_path.simpleName.split("_1")[0]
    }.ifEmpty("fresh_run").set{ existing_id }

    CRAM_EXTRACT(meta_cram_ch)

    emit:
    reads_ch = CRAM_EXTRACT.out.reads_ch
}

